initial_robot_configuration:

  ###############################
  # Initial robot configuration #
  ###############################

  com: [0.0, 0.15, -0.20]
  amom: [0.0, 0.0, 0.0]
  lmom: [0.0, 0.0, 0.0]
  eef_ctrl:
    eef_frc_rf: [0.0, 0.0, 0.5]
    eef_frc_lf: [0.0, 0.0, 0.5]
    eef_frc_rh: [0.0, 0.0, 0.0]
    eef_frc_lh: [0.0, 0.0, 0.0]
  eef_pose:
    eef_rf: [1.0,    0.086, 0.15, -0.92,    1.0, 0.0, 0.0, 0.0]
    eef_lf: [1.0,   -0.086, 0.15, -0.92,    1.0, 0.0, 0.0, 0.0]
    eef_rh: [0.0,    0.400, 0.30,  0.00,    0.0, -0.70711, 0.70711, 0.0 ]
    eef_lh: [0.0,   -0.400, 0.30,  0.00,    0.70711, 0.0, 0.0,  0.70711 ]


terrain_description:

  #######################
  # Terrain description #
  #######################

  regions: [ [[0.196053, 0.65, -1.04053], [0.103947, 0.65, -1.07947], [0.103947, 0.55, -1.07947], [0.196053, 0.55, -1.04053]]       ,
             [[0.23, 1.25, -1], [0.13, 1.25, -1], [0.13, 1.15, -1], [0.23, 1.15, -1]]                                               ,
             [[0.226053, 1.85, -0.930529], [0.133947, 1.85, -0.969471], [0.133947, 1.75, -0.969471], [0.226053, 1.75, -0.930529]]   ,
             [[-0.0839469, 0.4, -0.969471], [-0.176053, 0.4, -0.930529], [-0.176053, 0.3, -0.930529], [-0.0839469, 0.3, -0.969471]] ,
             [[-0.1, 0.95, -0.96], [-0.2, 0.95, -0.96], [-0.2, 0.85, -0.96], [-0.1, 0.85, -0.96]]                                   ,
             [[-0.1, 1.55, -0.98], [-0.2, 1.55, -0.98], [-0.2, 1.45, -0.98], [-0.1, 1.45, -0.98]]                                   ]


contact_plan:

  ################
  # Contact plan #
  ################

  effcnt_rf: [[ 0.0,  2.0,    0.086, 0.15, -0.92,    1.0, 0.0, 0.0, 0.0,           1.0,   -1.0],
              [ 4.0,  9.0,    0.280, 0.45, -1.12,    0.9689, 0.0, -0.2474, 0.0,    1.0,   -1.0],
              [12.0, 16.0,    0.350, 0.98, -1.45,    1.0, 0.0, 0.0, 0.0,           1.0,   -1.0],
              [18.0, 22.0,    0.300, 1.35, -1.27,    0.9689, 0.0, -0.2474, 0.0,    1.0,   -1.0],
              [24.0, 30.0,    0.186, 1.80, -0.97,    1.0, 0.0, 0.0, 0.0,           1.0,   -1.0]]
  effcnt_lf: [[ 0.0,  5.0,   -0.086, 0.15, -0.92,    1.0, 0.0, 0.0, 0.0,           1.0,   -1.0],
              [ 8.0, 13.0,   -0.180, 0.70, -1.27,    0.96891, 0.0,  0.2474, 0.0,   1.0,   -1.0],
              [15.0, 19.0,   -0.100, 1.25, -1.45,    1.0, 0.0, 0.0, 0.0,           1.0,   -1.0],
              [21.0, 25.0,   -0.180, 1.55, -1.12,    0.96891, 0.0,  0.2474, 0.0,   1.0,   -1.0],
              [27.0, 30.0,   -0.186, 1.90, -0.97,    1.0, 0.0, 0.0, 0.0,           1.0,   -1.0]]
  effcnt_rh: []
  effcnt_lh: []


planner_variables:

  #######################
  # Dynamics parameters #
  #######################

  heuristic: TrustRegion  # Types: TrustRegion, SoftConstraint, TimeOptimization #
  n_act_eefs: 2
  time_step: 0.15
  time_horizon: 29.5
  external_force: [0.00, 0.00, 0.00]
  com_displacement: [0.00, 1.70, -0.05]
  num_com_viapoints: 0
  com_viapoints:
    via0: [2.50,    0.500, 0.45,  0.00]

  #####################
  # Timing parameters #
  #####################

  max_time_iterations: 100
  max_time_residual_tolerance: 1e-3
  min_time_residual_improvement: 1e-5

  ############################
  # Configuration parameters #
  ############################

  gravity: 9.81
  robot_mass: 60.00
  friction_coeff: 1.0
  friction_cone: LinearCone  # Types: LinearCone, SocCone #
  torque_range: [-200.0, 200.0]
  eff_offset_rf: [ 0.00,  0.00,  0.00]
  eff_offset_lf: [ 0.00,  0.00,  0.00]
  eff_offset_rh: [ 0.20,  0.00,  0.48]
  eff_offset_lh: [-0.20,  0.00,  0.48]
  cop_range_rf: [-0.03,  0.03, -0.08,  0.08]
  cop_range_lf: [-0.03,  0.03, -0.08,  0.08]
  cop_range_rh: [-0.03,  0.03, -0.03,  0.03]
  cop_range_lh: [-0.03,  0.03, -0.03,  0.03]
  max_eef_lengths: [0.82,  0.82,  0.60,  0.60]

  ####################
  # Dynamics weights #
  ####################

  w_trq_arm:       1.000
  w_trq_leg:       1.000
  w_com:           [ 10000,  10000,  10000]
  w_amom:          [ 0.010,  0.010,  0.010]
  w_lmom:          [ 0.010,  0.010,  0.010]
  w_amomd:         [ 0.020,  0.020,  0.020]
  w_lmomd:         [ 0.010,  0.010,  0.010]
  w_amom_final:    [ 10.00,  10.00,  10.00]
  w_lmom_final:    [ 10.00,  10.00,  10.00]
  w_com_via:       [ 0.000,  0.000,  0.000]
  w_frc_arm:       [ 0.001,  0.001,  0.001]
  w_frc_leg:       [ 0.001,  0.001,  0.001]
  w_dfrc_arm:      [ 0.000,  0.000,  0.000]
  w_dfrc_leg:      [ 0.000,  0.000,  0.000]
  w_amom_track:    [ 1.000,  1.000,  1.000]
  w_lmom_track:    [ 0.100,  0.100,  0.100]
    
  #######################
  # Storage information #
  #######################

  store_data: True

  ##################
  # Solver setting #
  ##################
  
  use_default_solver_setting: True