initial_robot_configuration:

  ###############################
  # Initial robot configuration #
  ###############################

  com: [0.0, 0.0, -0.1]
  amom: [0.0, 0.0, 0.0]
  lmom: [0.0, 0.0, 0.0]
  eef_ctrl:
    eef_frc_rf: [0.0, 0.0, 0.25]
    eef_frc_lf: [0.0, 0.0, 0.25]
    eef_frc_rh: [0.0, 0.0, 0.25]
    eef_frc_lh: [0.0, 0.0, 0.25]
  eef_pose:
    eef_rf: [1.0,   -0.10, -0.20, -0.32,    1.0, 0.0, 0.0, 0.0]
    eef_lf: [1.0,   -0.10,  0.20, -0.32,    1.0, 0.0, 0.0, 0.0]
    eef_rh: [1.0,    0.10, -0.20, -0.32,    1.0, 0.0, 0.0, 0.0]
    eef_lh: [1.0,    0.10,  0.20, -0.32,    1.0, 0.0, 0.0, 0.0]


terrain_description:

  #######################
  # Terrain description #
  #######################

  regions: [ [[ 1.00,  1.00, -0.32], [-1.00,  1.00, -0.32], [-1.00, -1.00, -0.32], [ 1.00, -1.00, -0.32]] ]


contact_plan:

  ################
  # Contact plan #
  ################

  effcnt_rf: [[0.0, 5.0,   -0.10, -0.20, -0.32,    1.0, 0.0, 0.0, 0.0,    1.0,   -1.0]]
  effcnt_lf: [[0.0, 5.0,   -0.10,  0.20, -0.32,    1.0, 0.0, 0.0, 0.0,    1.0,   -1.0]]
  effcnt_rh: [[0.0, 5.0,    0.10, -0.20, -0.32,    1.0, 0.0, 0.0, 0.0,    1.0,   -1.0]]
  effcnt_lh: [[0.0, 5.0,    0.10,  0.20, -0.32,    1.0, 0.0, 0.0, 0.0,    1.0,   -1.0]]


planner_variables:

  #########################
  # Kinematics parameters #
  #########################
  
  load_kinematics: True
  num_dofs: 8
  active_dofs: [0, 1, 2, 3, 4, 5, 6, 7]
  min_joint_limits: [-2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5]
  max_joint_limits: [ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5]
  default_joint_positions: [0.52, -1.04,  0.52, -1.04, -0.52,  1.04, -0.52,  1.04]

  #######################
  # Dynamics parameters #
  #######################

  heuristic: SoftConstraint  # Types: TrustRegion, SoftConstraint, TimeOptimization #
  n_act_eefs: 4
  time_step: 0.1
  time_horizon: 2.0
  external_force: [0.00, 0.00, 0.00]
  com_displacement: [0.00, 0.00, 0.00]
  num_com_viapoints: 1
  com_viapoints:
    via0: [1.0,    0.00, 0.00, -0.20]

  #####################
  # Timing parameters #
  #####################

  max_time_iterations: 50
  max_time_residual_tolerance: 1e-2
  min_time_residual_improvement: 1e-4

  ############################
  # Configuration parameters #
  ############################

  gravity: 9.81
  robot_mass: 2.772
  friction_coeff: 1.0
  friction_cone: LinearCone  # Types: LinearCone, SocCone #
  torque_range: [-200.0, 200.0]
  eff_offset_rf: [-0.10, -0.20,  0.00]
  eff_offset_lf: [-0.10,  0.20,  0.00]
  eff_offset_rh: [ 0.10, -0.20,  0.00]
  eff_offset_lh: [ 0.10,  0.20,  0.00]
  cop_range_rf: [-0.00,  0.00, -0.00,  0.00]
  cop_range_lf: [-0.00,  0.00, -0.00,  0.00]
  cop_range_rh: [-0.00,  0.00, -0.00,  0.00]
  cop_range_lh: [-0.00,  0.00, -0.00,  0.00]
  max_eef_lengths: [0.30,  0.30,  0.30,  0.30]

  ####################
  # Dynamics weights #
  ####################

  w_trq_arm:       1.000
  w_trq_leg:       1.000
  w_com:           [ 10000,  10000,  10000]
  w_amom:          [ 0.500,  0.500,  0.500]
  w_lmom:          [ 0.010,  0.001,  0.001]
  w_amomd:         [ 0.100,  0.400,  0.100]
  w_lmomd:         [ 0.015,  0.015,  0.015]
  w_amom_final:    [ 10.00,  10.00,  10.00]
  w_lmom_final:    [ 10.00,  10.00,  10.00]
  w_com_via:       [ 100.0,  100.0,  100.0]
  w_frc_arm:       [ 0.001,  0.001,  0.001]
  w_frc_leg:       [ 0.001,  0.001,  0.001]
  w_dfrc_arm:      [ 0.000,  0.000,  0.000]
  w_dfrc_leg:      [ 0.000,  0.000,  0.000]
  w_amom_track:    [ 1.000,  1.000,  1.000]
  w_lmom_track:    [ 0.100,  0.100,  0.100]

  ######################
  # Kinematics weights #
  ######################

  max_convergence_iters: 50
  convergence_tolerance:  1e-4
  
  w_kin_com:      [ 10.00,   10.00,   10.00]
  w_kin_eff_pos:  [ 6.000,   6.000,   6.000]
  #w_track_eff_ori:  [ 50.00,   50.00,   50.00]
  #w_track_base_ori: [ 1.000,   1.000,   1.000]
  w_kin_amom:     [ 4.e-3,   4.e-2,   4.e-3]
  w_kin_lmom:     [ 1.e-3,   1.e-3,   1.e-3]
  w_kin_lmomd:      [ 1.e-5,   1.e-5,   1.e-5]
  w_kin_amomd:      [ 1.e-3,   5.e-3,   1.e-3]
  w_kin_default_joints: [                                        1e-2, 1e-2, 1e-2, 1e-2,  1e-2, 1e-2, 1e-2, 1e-2]
  w_kin_joint_vel:      [1e-5, 1e-5, 1e-5,  1e+1, 1e+1, 1e+1,    1e-5, 1e-5, 1e-5, 1e-5,  1e-5, 1e-5, 1e-5, 1e-5]
  w_kin_joint_acc:      [1e-5, 1e-5, 1e-5,  1e+1, 1e+1, 1e+1,    1e-5, 1e-5, 1e-5, 1e-5,  1e-5, 1e-5, 1e-5, 1e-5]
                         # floating base                         # joints     

  #######################
  # Storage information #
  #######################

  store_data: True

  ##################
  # Solver setting #
  ##################
  
  use_default_solver_setting: True